server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
      #Route Mapping
      - id: hr-worker               #RouteIdentifier
        uri: http://localhost:8001/         #Respective microservice URL which needs to be mappe
        predicates:
        - Path=/workers/**          #Request Context Path Mapping

        #Route Mapping
      - id: hr-payroll
        uri: http://localhost:8101/
        predicates:
        - Path=/payments/** 
        
      - id: hr-user
        uri: http://localhost:8002/
        predicates:
        - Path=/users/**       enabled: true
        
  eureka:
     instance:
       hostname: localhost
       client:
            serviceUrl:
                defaultZone: http://localhost:8761/eureka
                